import {
  UserProfile,
  Beneficiary,
  Transaction,
  EliteCreditCard,
  NotificationItem,
  TestControlState,
  AppThemeMode,
  AppLanguage,
  TransferRail,
} from '../types';

export const INITIAL_USER: UserProfile = {
  name: 'Sanjay G',
  balance: 24588338510.7,
  accountNumber: '**** **** 4588',
  rawAccountNumber: '458890123456',
  accountType: 'Ultra High Net Worth Private Banking',
  currency: 'USD',
  creditScore: 850,
  creditRating: 'World Elite / Exceptional',
  bankingScore: 998,
  creditLimit: 5000000.0,
  availableCredit: 4825000.0,
  usedCredit: 175000.0,
  nextPayment: 12500.0,
  paymentDue: 'Oct 15, 2026',
  kycStatus: 'Verified',
  phone: '+1 (555) 019-4588',
  email: 'sanjay.g@testgrid.demo',
  address: '458 Tech Park Blvd, Suite 200, San Jose, CA 95110',
  dob: '14 Aug 1988',
  ifsc: 'TGBN0004588',
  upiId: 'sanjay@tg',
  relationshipManager: 'Priya Menon • Private Banking Desk',
  clientSince: '2012',
  tier: 'Black Diamond Ultra',
};

export const INITIAL_BENEFICIARIES: Beneficiary[] = [
  {
    id: 'BEN001',
    name: 'Aarav Mehta',
    nickname: 'Aarav',
    account: '998877665544',
    ifsc: 'HDFC0001234',
    bank: 'HDFC Bank',
    rail: 'IMPS',
    isFavorite: true,
    isVerified: true,
  },
  {
    id: 'BEN002',
    name: 'Priya Sharma',
    nickname: 'Priya',
    account: '112233445566',
    ifsc: 'ICIC0005678',
    bank: 'ICICI Bank',
    rail: 'NEFT',
    isFavorite: true,
    isVerified: true,
  },
  {
    id: 'BEN003',
    name: 'Global Holdings LLC',
    nickname: 'Global HQ',
    account: '445566778899',
    ifsc: '021000021',
    bank: 'JPMorgan Chase',
    rail: 'ACH',
    isVerified: true,
  },
  {
    id: 'BEN004',
    name: 'Singapore Trust Co',
    nickname: 'SG Trust',
    account: '778899001122',
    ifsc: 'DBSSSGSGXXX',
    bank: 'DBS Bank',
    rail: 'RTGS',
    isVerified: true,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'TGX202609160001',
    title: 'Amazon',
    recipientOrMerchant: 'Amazon.com Payments',
    amount: 249.99,
    isCredit: false,
    type: 'CARD',
    timestamp: 'Sep 16, 2026, 14:22',
    status: 'Completed',
    category: 'Shopping',
    note: 'Electronics order #402-99128',
    referenceId: 'REF-AMZ-991280',
  },
  {
    id: 'TGX202609160002',
    title: 'Salary Credit',
    recipientOrMerchant: 'TestGrid Technologies Inc',
    amount: 15000.0,
    isCredit: true,
    type: 'SALARY',
    timestamp: 'Sep 15, 2026, 09:00',
    status: 'Completed',
    category: 'Income',
    note: 'Monthly Payroll Deposit',
    referenceId: 'REF-PAY-20260915',
  },
  {
    id: 'TGX202609150003',
    title: 'Starbucks',
    recipientOrMerchant: 'Starbucks Coffee #301',
    amount: 18.45,
    isCredit: false,
    type: 'CARD',
    timestamp: 'Sep 15, 2026, 08:45',
    status: 'Completed',
    category: 'Food',
    note: 'Breakfast & Espresso',
    referenceId: 'REF-SBX-084511',
  },
  {
    id: 'TGX202609140004',
    title: 'UPI Payment',
    recipientOrMerchant: 'TG Demo Store',
    amount: 125.0,
    isCredit: false,
    type: 'UPI',
    timestamp: 'Sep 14, 2026, 17:30',
    status: 'Completed',
    category: 'Shopping',
    note: 'QR Payment at Store',
    referenceId: 'UPI-DEMO-789012',
    rail: 'UPI',
  },
  {
    id: 'TGX202609130005',
    title: 'IMPS Transfer',
    recipientOrMerchant: 'Aarav Mehta',
    amount: 250000.0,
    isCredit: false,
    type: 'IMPS',
    timestamp: 'Sep 13, 2026, 11:05',
    status: 'Completed',
    category: 'Transfers',
    note: 'Family transfer',
    referenceId: 'REF-IMP-445889',
    rail: 'IMPS',
  },
  {
    id: 'TGX202609120006',
    title: 'Electricity Bill',
    recipientOrMerchant: 'Pacific Gas & Electric',
    amount: 186.4,
    isCredit: false,
    type: 'BILL_PAY',
    timestamp: 'Sep 12, 2026, 16:10',
    status: 'Completed',
    category: 'Bills',
    note: 'Account 445-9921',
    referenceId: 'REF-PGE-88129',
  },
  {
    id: 'TGX202609100007',
    title: 'Dividend Credit',
    recipientOrMerchant: 'Vanguard Index Fund',
    amount: 87500.0,
    isCredit: true,
    type: 'SALARY',
    timestamp: 'Sep 10, 2026, 08:00',
    status: 'Completed',
    category: 'Income',
    note: 'Quarterly dividend',
    referenceId: 'REF-VAN-100234',
  },
];

export const INITIAL_CREDIT_CARDS: EliteCreditCard[] = [
  {
    id: 'CARD001',
    name: 'TG Black Diamond Infinite',
    tier: 'World Elite',
    cardNumber: '**** **** **** 8899',
    expiry: '12/30',
    holder: 'SANJAY G',
    limit: 2500000,
    available: 2412500,
    used: 87500,
    perks: 'Unlimited lounge + 5% cashback on travel',
    gradient: 'from-slate-900 via-zinc-900 to-black',
  },
  {
    id: 'CARD002',
    name: 'TG Invitation-Only Metal',
    tier: 'Private Invitation',
    cardNumber: '**** **** **** 4588',
    expiry: '09/29',
    holder: 'SANJAY G',
    limit: 2500000,
    available: 2412500,
    used: 87500,
    perks: 'Concierge 24/7 + private jet credits',
    gradient: 'from-amber-900/90 via-stone-800 to-black',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'N1',
    title: 'Transfer Successful',
    message: 'IMPS of $250,000.00 to Aarav Mehta completed.',
    timestamp: 'Sep 13, 11:06',
    isRead: false,
    type: 'transfer',
  },
  {
    id: 'N2',
    title: 'Security Alert',
    message: 'New device login detected from San Jose, CA.',
    timestamp: 'Sep 16, 09:12',
    isRead: false,
    type: 'security',
  },
  {
    id: 'N3',
    title: 'Credit Card Due',
    message: 'Black Diamond card minimum due $8,750.00 by Oct 15.',
    timestamp: 'Sep 15, 18:00',
    isRead: true,
    type: 'credit',
  },
  {
    id: 'N4',
    title: 'KYC Verified',
    message: 'Your demo KYC profile is fully verified and active for global transactions.',
    timestamp: 'Sep 01, 10:00',
    isRead: true,
    type: 'kyc',
  },
  {
    id: 'N5',
    title: 'Exclusive Offer',
    message: 'Invitation-Only Metal card annual fee waived for UHNW clients this quarter.',
    timestamp: 'Sep 08, 12:30',
    isRead: false,
    type: 'offer',
  },
];

export const INITIAL_TEST_CONTROLS: TestControlState = {
  forceInsufficientBalance: false,
  forceTransactionFailure: false,
  simulateNetworkTimeout: false,
  simulateUnverifiedKyc: false,
  mockBiometricSuccess: false,
  requirePaymentAuth: true,
  forceOtpAlways: false,
};

let transactionSequence = 8;
export function generateNextTransactionId(): string {
  const seq = String(transactionSequence++).padStart(4, '0');
  return `TGX20260923${seq}`;
}

export function generateNextLoanId(): string {
  const randomNum = Math.floor(1000 + Math.random() * 9000);
  return `LN-2026-${randomNum}`;
}
