import { AppLanguage } from '../types';

export const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {
    appName: 'TG Bank Mobile',
    tagline: 'Secure Enterprise Banking',
    checkingAccount: 'Checking Account • 4588',
    welcomeBack: 'Welcome back,',
    online: 'Online',
    totalBalance: 'Total Available Balance',
    quickActions: 'Quick Actions',
    send: 'Send',
    receive: 'Receive',
    upiPay: 'UPI Pay',
    addMoney: 'Add Money',
    withdraw: 'Withdraw',
    payBills: 'Pay Bills',
    credit: 'Credit',
    kyc: 'KYC',
    spendingSummary: 'September 2026 Spending Summary',
    recentTransactions: 'Recent Transactions',
    viewAll: 'View All',
    shopping: 'Shopping',
    food: 'Food',
    bills: 'Bills',
    transfers: 'Transfers',
    entertainment: 'Entertainment',
    signIn: 'Sign In Securely',
    biometricSignIn: 'Login with Face ID / Touch ID',
    useDemo: 'Use Demo Credentials',
    forgotPin: 'Forgot PIN?',
    usernamePlaceholder: 'Username / Customer ID',
    pinPlaceholder: '4-digit Security PIN',
    demoAccount: 'Demo Account: Sanjay G / 1234',
    history: 'History',
    home: 'Home',
    payments: 'UPI & Pay',
    profile: 'Profile',
    testControls: 'Test Controls',
    creditScore: 'Credit Score',
    excellent: 'World Elite / Exceptional',
    applyLoan: 'Apply for Loan',
    requestIncrease: 'Request Limit Increase',
    statements: 'Download Statement',
    makePayment: 'Pay Credit Bill',
  },
  es: {
    appName: 'TG Bank Móvil',
    tagline: 'Banca Empresarial Segura',
    checkingAccount: 'Cuenta Corriente • 4588',
    welcomeBack: 'Bienvenido de nuevo,',
    online: 'En Línea',
    totalBalance: 'Saldo Disponible Total',
    quickActions: 'Acciones Rápidas',
    send: 'Enviar',
    receive: 'Recibir',
    upiPay: 'Pago UPI',
    addMoney: 'Ingresar',
    withdraw: 'Retirar',
    payBills: 'Pagar Facturas',
    credit: 'Crédito',
    kyc: 'KYC',
    spendingSummary: 'Resumen de Gastos Septiembre 2026',
    recentTransactions: 'Transacciones Recientes',
    viewAll: 'Ver Todo',
    shopping: 'Compras',
    food: 'Comida',
    bills: 'Facturas',
    transfers: 'Transferencias',
    entertainment: 'Entretenimiento',
    signIn: 'Iniciar Sesión Seguro',
    biometricSignIn: 'Iniciar con Face ID / Touch ID',
    useDemo: 'Credenciales Demo',
    forgotPin: '¿Olvidó su PIN?',
    usernamePlaceholder: 'Usuario / ID Cliente',
    pinPlaceholder: 'PIN de 4 dígitos',
    demoAccount: 'Cuenta Demo: Sanjay G / 1234',
    history: 'Historial',
    home: 'Inicio',
    payments: 'UPI y Pagos',
    profile: 'Perfil',
    testControls: 'Controles de Prueba',
    creditScore: 'Puntuación Crediticia',
    excellent: 'World Elite / Excepcional',
    applyLoan: 'Solicitar Préstamo',
    requestIncrease: 'Aumentar Límite',
    statements: 'Descargar Estado',
    makePayment: 'Pagar Factura de Crédito',
  },
  fr: {
    appName: 'TG Bank Mobile',
    tagline: 'Banque d’Entreprise Sécurisée',
    checkingAccount: 'Compte Chèque • 4588',
    welcomeBack: 'Bon retour,',
    online: 'En ligne',
    totalBalance: 'Solde Total Disponible',
    quickActions: 'Actions Rapides',
    send: 'Envoyer',
    receive: 'Recevoir',
    upiPay: 'Paiement UPI',
    addMoney: 'Ajouter',
    withdraw: 'Retirer',
    payBills: 'Factures',
    credit: 'Crédit',
    kyc: 'KYC',
    spendingSummary: 'Dépenses Septembre 2026',
    recentTransactions: 'Transactions Récentes',
    viewAll: 'Voir Tout',
    shopping: 'Achats',
    food: 'Alimentation',
    bills: 'Factures',
    transfers: 'Virements',
    entertainment: 'Loisirs',
    signIn: 'Connexion Sécurisée',
    biometricSignIn: 'Connexion Face ID / Touch ID',
    useDemo: 'Identifiants Démo',
    forgotPin: 'PIN oublié ?',
    usernamePlaceholder: 'Nom d’utilisateur',
    pinPlaceholder: 'Code PIN à 4 chiffres',
    demoAccount: 'Compte Démo : Sanjay G / 1234',
    history: 'Historique',
    home: 'Accueil',
    payments: 'UPI & Paiements',
    profile: 'Profil',
    testControls: 'Contrôles de Test',
    creditScore: 'Score de Crédit',
    excellent: 'World Elite / Exceptionnel',
    applyLoan: 'Demander un Prêt',
    requestIncrease: 'Augmenter Plafond',
    statements: 'Télécharger Relevé',
    makePayment: 'Payer Carte de Crédit',
  },
  hi: {
    appName: 'टीजी बैंक मोबाइल',
    tagline: 'सुरक्षित एंटरप्राइज बैंकिंग',
    checkingAccount: 'चालू खाता • 4588',
    welcomeBack: 'पुनः स्वागत है,',
    online: 'ऑनलाइन',
    totalBalance: 'कुल उपलब्ध शेष राशि',
    quickActions: 'त्वरित सेवाएं',
    send: 'पैसे भेजें',
    receive: 'पैसे प्राप्त करें',
    upiPay: 'यूपीआई भुगतान',
    addMoney: 'पैसे जोड़ें',
    withdraw: 'निकासी',
    payBills: 'बिल भरें',
    credit: 'क्रेडिट',
    kyc: 'केवाईसी',
    spendingSummary: 'सितंबर 2026 खर्च विवरण',
    recentTransactions: 'हाल के लेनदेन',
    viewAll: 'सभी देखें',
    shopping: 'खरीदारी',
    food: 'खान-पान',
    bills: 'उपयोगिता बिल',
    transfers: 'स्थानांतरण',
    entertainment: 'मनोरंजन',
    signIn: 'सुरक्षित लॉगिन करें',
    biometricSignIn: 'फेस आईडी / बायोमेट्रिक से लॉगिन',
    useDemo: 'डेमो विवरण भरें',
    forgotPin: 'पिन भूल गए?',
    usernamePlaceholder: 'उपयोगकर्ता नाम / ग्राहक आईडी',
    pinPlaceholder: '4-अंकीय सुरक्षा पिन',
    demoAccount: 'डेमो खाता: Sanjay G / 1234',
    history: 'इतिहास',
    home: 'होम',
    payments: 'भुगतान',
    profile: 'प्रोफाइल',
    testControls: 'परीक्षण नियंत्रण',
    creditScore: 'क्रेडिट स्कोर',
    excellent: 'वर्ल्ड एलिट / असाधारण',
    applyLoan: 'ऋण के लिए आवेदन',
    requestIncrease: 'क्रेडिट सीमा बढ़ाएं',
    statements: 'स्टेटमेंट डाउनलोड करें',
    makePayment: 'क्रेडिट बिल भुगतान',
  },
  de: {
    appName: 'TG Bank Mobile',
    tagline: 'Sicheres Enterprise Banking',
    checkingAccount: 'Girokonto • 4588',
    welcomeBack: 'Willkommen zurück,',
    online: 'Online',
    totalBalance: 'Verfügbares Gesamtsaldo',
    quickActions: 'Schnellaktionen',
    send: 'Überweisen',
    receive: 'Empfangen',
    upiPay: 'UPI Zahlung',
    addMoney: 'Einzahlen',
    withdraw: 'Abheben',
    payBills: 'Rechnungen',
    credit: 'Kredit',
    kyc: 'KYC',
    spendingSummary: 'Ausgaben September 2026',
    recentTransactions: 'Letzte Umsätze',
    viewAll: 'Alle anzeigen',
    shopping: 'Einkauf',
    food: 'Essen',
    bills: 'Rechnungen',
    transfers: 'Überweisungen',
    entertainment: 'Unterhaltung',
    signIn: 'Sicher Anmelden',
    biometricSignIn: 'Mit Face ID / Touch ID anmelden',
    useDemo: 'Demo-Daten füllen',
    forgotPin: 'PIN vergessen?',
    usernamePlaceholder: 'Benutzername / Kunden-ID',
    pinPlaceholder: '4-stellige PIN',
    demoAccount: 'Demo-Konto: Sanjay G / 1234',
    history: 'Verlauf',
    home: 'Übersicht',
    payments: 'Zahlungen',
    profile: 'Profil',
    testControls: 'Teststeuerungen',
    creditScore: 'Bonitäts-Score',
    excellent: 'World Elite / Außergewöhnlich',
    applyLoan: 'Kredit beantragen',
    requestIncrease: 'Limit erhöhen',
    statements: 'Kontoauszug laden',
    makePayment: 'Kreditkarte begleichen',
  },
  ja: {
    appName: 'TG Bank モバイル',
    tagline: 'エンタープライズ・セキュアバンキング',
    checkingAccount: '当座預金 • 4588',
    welcomeBack: 'お帰りなさい、',
    online: 'オンライン',
    totalBalance: '利用可能残高合計',
    quickActions: 'クイックアクション',
    send: '送金',
    receive: '受取',
    upiPay: 'UPI決済',
    addMoney: '入金',
    withdraw: '出金',
    payBills: '請求書支払',
    credit: 'クレジット',
    kyc: '本人確認 (KYC)',
    spendingSummary: '2026年9月の支出サマリー',
    recentTransactions: '最近の取引履歴',
    viewAll: 'すべて見る',
    shopping: 'ショッピング',
    food: '飲食',
    bills: '公共料金',
    transfers: '振替',
    entertainment: 'エンタメ',
    signIn: '安全にログイン',
    biometricSignIn: '生体認証でログイン',
    useDemo: 'デモ認証情報を使用',
    forgotPin: 'PINをお忘れですか？',
    usernamePlaceholder: 'ユーザー名 / 顧客ID',
    pinPlaceholder: '4桁の暗証番号',
    demoAccount: 'デモ口座: Sanjay G / 1234',
    history: '取引履歴',
    home: 'ホーム',
    payments: '送金・決済',
    profile: 'プロフィール',
    testControls: 'テスト制御',
    creditScore: '信用スコア',
    excellent: 'ワールドエリート / 卓越',
    applyLoan: '融資を申し込む',
    requestIncrease: '限度額引き上げ申請',
    statements: '明細書ダウンロード',
    makePayment: 'カード代金支払',
  },
};

export function t(key: string, lang: AppLanguage = 'en'): string {
  return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en']?.[key] || key;
}
